### ISSUE TITLE
warning message: was built for newer iOS version (14.0) than being linked (11.0)

### ISSUE THREAD

**Issue by jangsy7883** [cauly/iOS-SDK#1]
저희 앱은 iOS11 부터 지원하고 있습니다. 이번에 업데이트된 Cauly SDK 3.1.10를 추가한 후 제목과 같은 경고 메시지가 나타나고 있습니다. 
확인 부탁드립니다.

**Comment by cauly** [comment]
안녕하세요.
Cauly 입니다.

문의주신 내용에 대해 확인하여
iOS SDK 버전 3.1.11 으로 수정 배포되었습니다.
번거로우시겠지만
해당 버전으로 재확인 부탁드리겠습니다.

감사합니다.

**Comment by jangsy7883** [comment]
해결 되었습니다. 감사합니다.
