### ISSUE TITLE
The linked library 'libCauly-universal.a' is missing one or more architectures required by this target: armv7.

### ISSUE THREAD

**Issue by hnroh-adx** [cauly/iOS-SDK#2]
3.1.14 버전으로 업데이트를 하려고 했는데 아래 오류가 발생하면서 빌드가 되지 않습니다.
`The linked library 'libCauly-universal.a' is missing one or more architectures required by this target: armv7.`

<img width="351" alt="스크린샷 2021-06-10 오후 1 25 45" src="https://user-images.githubusercontent.com/77043786/121464985-e453dc80-c9ef-11eb-9e9b-5e92a953521f.png">

기존에 쓰고 있던 3.1.12 버전과 비교해보면  libCauly-universal.a에 armv7이 누락되어 있습니다.

libCauly-universal.a (3.1.14)
Architectures in the fat file: libCauly-universal.a are: x86_64 arm64 

libCauly-universal.a (3.1.12)
Architectures in the fat file: libCauly-universal.a are: armv7 x86_64 arm64

확인 부탁드립니다.

**Comment by cauly** [comment]
안녕하세요.
우선 Cauly SDK 를 사용해주셔서
감사의 말씀드립니다.

이슈 제기해주신 사항에 대해 검토해보니
armv7 아키텍쳐에 대해 누락된 것이 확인되어
방금 전 armv7 아키텍쳐 추가된 바이너리를 재적용해놨습니다.
사용에 불편을 드려 죄송한 말씀드립니다.

그럼, 언제든지 문의하실 내용이 있으면
다시 코멘트 부탁드립니다.
안녕히 계세요.

**Comment by adxcorp** [comment]
변경된 라이브러리로 적용했습니다. 감사합니다

**Comment by hnroh-adx** [comment]
변경된 라이브러리로 적용했습니다. 감사합니다
